### 新增
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "name": "zs",
  "age": 20,
  "tel": "13047894321",
  "entryTime": "2019-09-09"
}



### 删除
DELETE http://localhost:3000/api/users/1



### 修改
PUT http://localhost:3000/api/users/
Content-Type: application/json

{
  "name": "ls",
  "age": 25,
  "tel": "13047894321",
  "id": 1
}



### 查询
GET http://localhost:3000/api/users/2

