# Generated by Django 5.1.1 on 2024-10-28 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='分类名称', max_length=32, unique=True)),
                ('cover', models.ImageField(help_text='封面', upload_to='category_covers')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='是否删除')),
            ],
            options={
                'verbose_name': '教程分类',
                'verbose_name_plural': '教程分类',
                'db_table': 'video_category',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singer', models.CharField(help_text='歌手', max_length=128)),
                ('songName', models.CharField(help_text='音乐名', max_length=128)),
                ('cover', models.URLField(help_text='封面', max_length=512)),
                ('play_url', models.ImageField(help_text='本地播放地址', upload_to='musics')),
                ('remote_url', models.CharField(help_text='酷狗播放地址', max_length=128)),
                ('lyrics', models.TextField(help_text='歌词')),
                ('views', models.IntegerField(default=0, help_text='播放量')),
                ('likes', models.IntegerField(default=0, help_text='点赞量')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新时间')),
            ],
            options={
                'verbose_name': '音乐',
                'verbose_name_plural': '音乐',
                'db_table': 'music',
            },
        ),
        migrations.CreateModel(
            name='VideoTutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='标题', max_length=32, unique=True)),
                ('summary', models.CharField(help_text='概要', max_length=128)),
                ('cover', models.ImageField(help_text='视频封面', upload_to='video_covers')),
                ('play_url', models.FileField(help_text='播放地址', upload_to='videos')),
                ('views', models.IntegerField(default=0, help_text='播放量')),
                ('likes', models.IntegerField(default=0, help_text='点赞量')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('is_deleted', models.BooleanField(default=False, help_text='是否删除')),
                ('is_paid', models.BooleanField(default=False, help_text='是否付费')),
                ('category', models.ForeignKey(help_text='视频分类', on_delete=django.db.models.deletion.CASCADE, to='app.category')),
            ],
            options={
                'verbose_name': '视频资源',
                'verbose_name_plural': '视频资源',
                'db_table': 'video_series',
                'ordering': ['-created_at'],
            },
        ),
    ]
